version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - VNC_PASSWD=$VNC_PASSWD
      - PORT=6910
      - SCREEN_WIDTH=1600
      - SCREEN_HEIGHT=900
      - MT_URL=https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe
      - USER_MOUNT_FOLDER=/home/ubuntu/.wine
    ports:
      - 6910:6910
    volumes:
      - ./.docker:/home/ubuntu/.wine
